#!/bin/bash

set -e
set -x

PATH_I3_GNOME="/usr/bin/i3-gnome"
PATH_I3_GNOME_DESKTOP="/usr/share/applications/i3-gnome.desktop"
PATH_I3_GNOME_SESSION="/usr/share/gnome-session/sessions/i3-gnome.session"
PATH_I3_GNOME_XSESSION="/usr/share/xsessions/i3-gnome.desktop"

#
# Test installation
#

sudo make install

test -f "${PATH_I3_GNOME}"
test -f "${PATH_I3_GNOME_DESKTOP}"
test -f "${PATH_I3_GNOME_SESSION}"
test -f "${PATH_I3_GNOME_XSESSION}"

#
# Test uninstallation
#

sudo make uninstall

test ! -f "${PATH_I3_GNOME}"
test ! -f "${PATH_I3_GNOME_DESKTOP}"
test ! -f "${PATH_I3_GNOME_SESSION}"
test ! -f "${PATH_I3_GNOME_XSESSION}"
